spring:
  main:
    allow-bean-definition-overriding: true
    devtools:
      livereload:
        enabled: true
      restart:
        enabled: true
  profiles:
    # db 설정 파일, local (logback 설정 파일)
    include: db, local

logging:
  level:
    root: info

    org:
      # SpringFramework Logging
      springframework: debug
