spring:
  main:
    allow-bean-definition-overriding: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  # DB h2
  datasource:
    url: jdbc:h2:~/docker/h2/data/security-db-auth
  # DB Jpa 설정
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  thymeleaf:
    cache: false

logging:
  level:
    springframework: debug

